### ISSUE TITLE
append_to_family

### ISSUE THREAD

**Issue by no-such-anthony** [mpenning/ciscoconfparse#103]
Hi.  There appears to be some issues with append_to_family in both 1.3.11 and 1.3.12.  The issues don't appear in 1.3.10.

The first issue can be replicated using the example in the documentation.

```
PS C:\vagrant\workspace\dev\c3> .\test.py
Traceback (most recent call last):
  File "C:\vagrant\workspace\dev\c3\test.py", line 15, in <module>
    obj.append_to_family(' carrier-delay msec 500')
  File "C:\Program Files\Python35\lib\site-packages\ciscoconfparse\ccp_abc.py", line 345, in append_to_family
    atomic=True)
  File "C:\Program Files\Python35\lib\site-packages\ciscoconfparse\ciscoconfparse.py", line 2571, in insert_after
    ii = self._list.index(robj)
ValueError: <IOSCfgLine # 5 ' ip address 1.1.1.5 255.255.255.252' (parent is # 4)> is not in list
```

The other issue I see is that it if doesn't break like above, it will stop processing objects in the loop.  When the loop gets to the second interface it doesn't process the deletes.

```
import re
from ciscoconfparse import CiscoConfParse

config = [
    '!',
    'interface Port-channel1',
    ' description up=fix03-d01,cm=Po2',
    ' switchport trunk native vlan 2',
    ' switchport trunk allowed vlan 200,779,1030,1056,1140,1155,1227',
    ' switchport mode trunk',
    ' switchport nonegotiate',
    '!',
    'interface GigabitEthernet0/47',
    'description up=fix03-d01,cm=G1/0/2 ',
    'switchport trunk native vlan 2',
    'switchport trunk allowed vlan 200,779,1030,1056,1140,1155,1227',
    'switchport mode trunk',
    'switchport nonegotiate',
    'srr-queue bandwidth share 1 30 35 5',
    'priority-queue out',
    'mls qos trust dscp',
    'channel-group 1 mode on',
    '!'
]

cfg = CiscoConfParse(config, factory=True)
interfaces = cfg.find_objects(r'^interface (.*)$')
for v in interfaces:
    for d in v.re_search_children(r"^ description "):
        if re.search(r'up=\D+\d+-d\d+,', d.text):
            if v.is_portchannel:
                v.append_to_family(' no port-channel standalone-disable')
            v.delete_children_matching(r'switchport nonegotiate')
            v.delete_children_matching(r'switchport trunk allowed vlan')
    v.delete_children_matching(r'srr-queue')
    v.delete_children_matching(r'switchport trunk pruning vlan none')
    v.delete_children_matching(r'mls qos')

for line in cfg.ioscfg:
    print(line)
```

**Comment by secondnope** [comment]
Hi,
I've discovered the same issue since version 1.3.11. With all former versions the example is working fine so far. 
However, on your second issue it seems there is a missing commit(). 
```
...
    v.delete_children_matching(r'mls qos')
# add a commit before read cfg again
cfg.commit()
for line in cfg.ioscfg:
    print(line)
```
Let me know, if your second issue is fixed with a commit.

**Comment by no-such-anthony** [comment]
Commit doesn't help.  Only going back to 1.3.10 seems to work.

Here is modified code, fixing the config indent I had in the test script, and including the suggested commit. 

```
import re
from ciscoconfparse import CiscoConfParse

config = [
    '!',
    'interface Port-channel1',
    ' description up=fix03-d01,cm=Po2',
    ' switchport trunk native vlan 2',
    ' switchport trunk allowed vlan 200,779,1030,1056,1140,1155,1227',
    ' switchport mode trunk',
    ' switchport nonegotiate',
    '!',
    'interface GigabitEthernet0/47',
    ' description up=fix03-d01,cm=G1/0/2 ',
    ' switchport trunk native vlan 2',
    ' switchport trunk allowed vlan 200,779,1030,1056,1140,1155,1227',
    ' switchport mode trunk',
    ' switchport nonegotiate',
    ' srr-queue bandwidth share 1 30 35 5',
    ' priority-queue out',
    ' mls qos trust dscp',
    ' channel-group 1 mode on',
    '!'
]

cfg = CiscoConfParse(config, factory=True)
interfaces = cfg.find_objects(r'^interface (.*)$')
for v in interfaces:
    for d in v.re_search_children(r"^ description "):
        if re.search(r'up=\D+\d+-d\d+,', d.text):
            if v.is_portchannel:
                v.append_to_family(' no port-channel standalone-disable')
            v.delete_children_matching(r'switchport nonegotiate')
            v.delete_children_matching(r'switchport trunk allowed vlan')
    v.delete_children_matching(r'srr-queue')
    v.delete_children_matching(r'switchport trunk pruning vlan none')
    v.delete_children_matching(r'mls qos')

cfg.commit()

for line in cfg.ioscfg:
    print(line)

```
