### ISSUE TITLE
Unable to Export into Excel using pandas

### ISSUE THREAD

**Issue by selvam33** [mpenning/ciscoconfparse#116]
TypeError: Unsupported type <class 'ciscoconfparse.models_cisco.IOSCfgLine'> in write()

Traceback (most recent call last):

  File "<ipython-input-33-d223fda36066>", line 4, in <module>
    con.to_excel(writer, sheet_name='CHENNAI')

  File "C:\Users\prart\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py", line 1424, in to_excel
    engine=engine)

  File "C:\Users\prart\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\excel.py", line 628, in write
    freeze_panes=freeze_panes)

  File "C:\Users\prart\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\excel.py", line 1600, in write_cells
    val, style)

  File "C:\Users\prart\AppData\Local\Continuum\anaconda3\lib\site-packages\xlsxwriter\worksheet.py", line 65, in cell_wrapper
    return method(self, *args, **kwargs)

  File "C:\Users\prart\AppData\Local\Continuum\anaconda3\lib\site-packages\xlsxwriter\worksheet.py", line 432, in write
    raise TypeError("Unsupported type %s in write()" % type(token))

TypeError: Unsupported type <class 'ciscoconfparse.models_cisco.IOSCfgLine'> in write()

I was able to export into CSV but when i use excelwriter its throwing Type error using pandas.

please help, thanks.

**Comment by mpenning** [comment]
> TypeError: Unsupported type <class 'ciscoconfparse.models_cisco.IOSCfgLine'> in write()

Please don't try to force xlsxwriter to figure out what to do with an IOSCfgLine object.  Assume the object is named `thislineobj`, you need to use `thislineobj.text` in xlsxwriter.
