### ISSUE TITLE
Error when importing ciscoconfparse

### ISSUE THREAD

**Issue by cslayton65** [mpenning/ciscoconfparse#118]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\cslayton2\AppData\Local\Programs\Python\Python37\Lib\site-packages\ciscoconfparse-1.3.20-py3.7.egg\ciscoconfparse\__init__.py", line 1, in <module>
    from .ciscoconfparse import *
  File "C:\Users\cslayton2\AppData\Local\Programs\Python\Python37\Lib\site-packages\ciscoconfparse-1.3.20-py3.7.egg\ciscoconfparse\ciscoconfparse.py", line 5536

    ^
SyntaxError: invalid syntax

**Comment by mpenning** [comment]
Please see https://github.com/mpenning/ciscoconfparse/issues/117
