### ISSUE TITLE
Address Value Error in Python 2.7.14

### ISSUE THREAD

**Issue by natarajan0007** [mpenning/ciscoconfparse#130]
>>> from ciscoconfparse import CiscoConfParse

Traceback (most recent call last):
  File "<pyshell#25>", line 1, in <module>
    from ciscoconfparse import CiscoConfParse
  File "D:\Printers\Python\Installation files\lib\site-packages\ciscoconfparse\__init__.py", line 1, in <module>
    from .ciscoconfparse import *
  File "D:\Printers\Python\Installation files\lib\site-packages\ciscoconfparse\ciscoconfparse.py", line 21, in <module>
    from .models_cisco import IOSHostnameLine, IOSRouteLine, IOSIntfLine
  File "D:\Printers\Python\Installation files\lib\site-packages\ciscoconfparse\models_cisco.py", line 599, in <module>
    class BaseIOSIntfLine(IOSCfgLine):
  File "D:\Printers\Python\Installation files\lib\site-packages\ciscoconfparse\models_cisco.py", line 1807, in BaseIOSIntfLine
    def in_ipv4_subnet(self, ipv4network=IPv4Obj('0.0.0.0/32', strict=False)):
  File "D:\Printers\Python\Installation files\lib\site-packages\ciscoconfparse\ccp_util.py", line 377, in __init__
    '{0}/{1}'.format(addr, masklen), strict=strict)
  File "D:\Printers\Python\Installation files\lib\site-packages\ipaddr.py", line 1625, in __init__
    self.network_address = IPv4Address(address)
  File "D:\Printers\Python\Installation files\lib\site-packages\ipaddr.py", line 1399, in __init__
    self._check_packed_address(address, 4)
  File "D:\Printers\Python\Installation files\lib\site-packages\ipaddr.py", line 554, in _check_packed_address
    expected_len, self._version))
AddressValueError: '0.0.0.0/32' (len 10 != 4) is not permitted as an IPv4 address. Did you pass in a bytes (str in Python 2) instead of a unicode object?

I am not even pass as a unicode object here in the source code in models_cisco.py", line 1807
   def in_ipv4_subnet(self, ipv4network=IPv4Obj('0.0.0.0/32', strict=False)):

due to this i am unable to import the package .

**Comment by mpenning** [comment]
No matter what I try, I haven't found a way to reproduce this problem.  Please provide more details such as the version of Windows you're running and the version of ciscoconfparse installed.
