### ISSUE TITLE
models_asa is broken in Python3.2 

### ISSUE THREAD

**Issue by mpenning** [mpenning/ciscoconfparse#14]
For now, I am removing Python3.2 from the Travis CI config...

```
(py32_test)[mpenning@tsunami fast]$ make test
cd ciscoconfparse; python ciscoconfparse.py; ./runtests.sh
................................
----------------------------------------------------------------------
Ran 32 tests in 0.061s

OK
.....FFF
======================================================================
FAIL: testL4Object_asa_lt01 (__main__.knownValues)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_Ccp_Util.py", line 56, in testL4Object_asa_lt01
    self.assertEqual(pp.port_list, range(1, 7))
AssertionError: range(1, 7) != range(1, 7)

======================================================================
FAIL: testL4Object_asa_lt02 (__main__.knownValues)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_Ccp_Util.py", line 61, in testL4Object_asa_lt02
    self.assertEqual(pp.port_list, range(1, 7))
AssertionError: range(1, 7) != range(1, 7)

======================================================================
FAIL: testL4Object_asa_range01 (__main__.knownValues)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_Ccp_Util.py", line 51, in testL4Object_asa_range01
    self.assertEqual(pp.port_list, range(25, 33))
AssertionError: range(25, 33) != range(25, 33)

----------------------------------------------------------------------
Ran 8 tests in 0.002s

FAILED (failures=3)
..........................................
----------------------------------------------------------------------
Ran 42 tests in 0.209s

OK
...F.
======================================================================
FAIL: testVal_object_group_service_02 (__main__.knownValues)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_Models_Asa.py", line 172, in testVal_object_group_service_02
    self.assertEqual(obj.ports, result_correct)
AssertionError: Lists differ: [<L4Object tcp [25]>, <L4Objec... != [<L4Object tcp [25]>, <L4Objec...

First differing element 2:
<L4Object tcp range(8080, 8082)>
<L4Object tcp range(8080, 8082)>

  [<L4Object tcp [25]>, <L4Object tcp [443]>, <L4Object tcp range(8080, 8082)>]

----------------------------------------------------------------------
Ran 5 tests in 0.008s

FAILED (failures=1)
make: *** [test] Error 1
(py32_test)[mpenning@tsunami fast]$
```

**Comment by mpenning** [comment]
Duplicate of Github issue #35
