### ISSUE TITLE
append_line breaks when using syntax='asa'

### ISSUE THREAD

**Issue by emabrad** [mpenning/ciscoconfparse#162]
Hello,

When taking an ASA configuration and attempting to append a line to the end of it, I receive the following traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "C:\Users\[REDACTEDPATH]\ciscoconfparse\ciscoconfparse.py", line 1626, in append_line
    self.ConfigObjs.append(linespec)
  File "C:\Users\[REDACTEDPATH]\ciscoconfparse\ciscoconfparse.py", line 3596, in append
    self.insert(list_idx, val, atomic)
TypeError: insert() takes 3 positional arguments but 4 were given
```

I have tried this in Python 3.6 as well as 3.7, to the same results.  I am using CiscoConfParse 1.4.3.

**Comment by mpenning** [comment]
This should be resolved in 1.4.4
