### ISSUE TITLE
CiscoConfParse.sync_diff fails with 'TypeError: object of type 'map' has no len()'

### ISSUE THREAD

**Issue by ptrhess** [mpenning/ciscoconfparse#218]
This issue is very similar to issue #214 in that there is a map being used where a sequence is expected, but this new error is being thrown from a different place, using `ciscoconfparse` v1.6.9.  Here is the backtrace from `ciscoconfparse` where it it used in a tool I wrote to make minimal delta changes to switch configs (in this case, a Dell Force10 S4810) for a test harness which exercises other gear with various link-aggregation failover scenarios:

```
    return self._baseconfig.sync_diff(self.config, r'.*')
  File "/fs/depot/python-modules/x64_linux/pyvenvs/3.6.13_2021_12_07/lib/python3.6/site-packages/ciscoconfparse/ciscoconfparse.py", line 2948, in sync_diff
    matcher = SequenceMatcher(isjunk=None, a=a_lines, b=b_lines)
  File "/fs/depot/python/x64_linux/3.6.13/python3.6/lib/python3.6/difflib.py", line 213, in __init__
    self.set_seqs(a, b)
  File "/fs/depot/python/x64_linux/3.6.13/python3.6/lib/python3.6/difflib.py", line 225, in set_seqs
    self.set_seq2(b)
  File "/fs/depot/python/x64_linux/3.6.13/python3.6/lib/python3.6/difflib.py", line 279, in set_seq2
    self.__chain_b()
  File "/fs/depot/python/x64_linux/3.6.13/python3.6/lib/python3.6/difflib.py", line 327, in __chain_b
    n = len(b)
TypeError: object of type 'map' has no len()
```

The object `self` seen in the first line of backtrace is a wrapper object containing the original switch config in the `_baseconfig` attribute and the modified switch config in the `config` attribute. Both of these attributes are `ciscoconfparse.CiscoConfParse` objects.

I can't say for sure where this behavior changed, since I upgraded `ciscoconfparse` from 1.5.46 to 1.6.7, where it started hitting issue #214. After upgrading again to 1.6.9, the code hits this new TypeError.

This is occurring on Python 3.6.13 for what its worth.

Digging into the `sync_diff` method, it looks like certain code paths will result in `a_lines` and `b_lines` remaining as maps rather than being materialized into lists. See `ciscoconfparse.py` lines 2935-2937 for example.

**Comment by ptrhess** [comment]
Confirmed that this fails on Python 3.10.1, using the `difflib` module provided in the 3.10 standard library as well. `difflib.SequenceMatcher` requires that the two sequences be materialized sequences of some sort.

**Comment by mpenning** [comment]
Hello @ptrhess 

Could you post an example to reproduce this problem? ciscoconfparse version 1.6.10 is probably best.

**Comment by ptrhess** [comment]
I can recreate the problem on ciscoconfparse 1.6.9, and can include a repro script as soon as I get the underlying configs sanitized. But I am unable to reproduce the issue on ciscoconfparse 1.6.10, at least with the configs that triggered the initial issue.

**Comment by ptrhess** [comment]
[repro218.tar.gz](https://github.com/mpenning/ciscoconfparse/files/7677844/repro218.tar.gz)

Attached file contains a repro script, and a pair of sanitized S4810 configs (IOS flavor) that reproduce the error.  Output with ciscoconfparse 1.6.9 looks like this:

```
$ python repro218.py
Traceback (most recent call last):
  File "/Users/phess/repro218.py", line 29, in <module>
    repro_218(sys.argv[1:])
  File "/Users/phess/repro218.py", line 23, in repro_218
    diff = bc.sync_diff(mc.ioscfg, r'.*')
  File "/usr/local/var/pyenv/versions/Test-3.10.0/lib/python3.10/site-packages/ciscoconfparse/ciscoconfparse.py", line 2948, in sync_diff
    matcher = SequenceMatcher(isjunk=None, a=a_lines, b=b_lines)
  File "/usr/local/var/pyenv/versions/3.10.0/lib/python3.10/difflib.py", line 182, in __init__
    self.set_seqs(a, b)
  File "/usr/local/var/pyenv/versions/3.10.0/lib/python3.10/difflib.py", line 194, in set_seqs
    self.set_seq2(b)
  File "/usr/local/var/pyenv/versions/3.10.0/lib/python3.10/difflib.py", line 248, in set_seq2
    self.__chain_b()
  File "/usr/local/var/pyenv/versions/3.10.0/lib/python3.10/difflib.py", line 296, in __chain_b
    n = len(b)
TypeError: object of type 'map' has no len()
```

Output with ciscoconfparse 1.6.10 looks like this:

```
$ python repro218.py
[
  "interface TenGigabitEthernet 0/8",
  " no  port-channel-protocol LACP ",
  "  no   port-channel 31 mode active ",
  "interface TenGigabitEthernet 0/9",
  " no  port-channel-protocol LACP ",
  "  no   port-channel 31 mode active ",
  "interface TenGigabitEthernet 0/25",
  " no  port-channel-protocol LACP ",
  "  no   port-channel 31 mode active ",
  "interface TenGigabitEthernet 0/27",
  " no  port-channel-protocol LACP ",
  "  no   port-channel 31 mode active ",
  "interface Vlan 1023",
  " no shutdown",
  " no  untagged TenGigabitEthernet 0/38-39",
  " no  untagged Port-channel 31-33",
... etc ...
]
```

**Comment by ptrhess** [comment]
It looks like the changes in 1.6.10 to materialize the maps into lists addressed the issue, such as [this update at line 2991](https://github.com/mpenning/ciscoconfparse/blob/master/ciscoconfparse/ciscoconfparse.py#L2991).

I think this issue can probably be closed, as of ciscoconfparse 1.6.10.
