### ISSUE TITLE
ciscoconfparse 1.2.11 & 1.2.12 won't install in Python3

### ISSUE THREAD

**Issue by mpenning** [mpenning/ciscoconfparse#25]
(py34_test)[mpenning@tsunami this]$ pip3 install --upgrade ciscoconfparse
    Downloading/unpacking ciscoconfparse from https://pypi.python.org/packages/source/c/ciscoconfparse/ciscoconfparse-1.2.12.tar.gz#md5=be0298e2d01471921b23c5860640fba4
      Downloading ciscoconfparse-1.2.12.tar.gz (225kB): 225kB downloaded
      Running setup.py (path:/opt/virtual_env/py34_test/build/ciscoconfparse/setup.py) egg_info for package ciscoconfparse
        Traceback (most recent call last):
          File "<string>", line 17, in <module>
          File "/opt/virtual_env/py34_test/build/ciscoconfparse/setup.py", line 14, in <module>
            from version_info.version import __version__ as __ccpversion__
          File "/opt/virtual_env/py34_test/build/ciscoconfparse/version_info/__init__.py", line 1, in <module>
            from version import *
        ImportError: No module named 'version'
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):

      File "<string>", line 17, in <module>

      File "/opt/virtual_env/py34_test/build/ciscoconfparse/setup.py", line 14, in <module>

        from version_info.version import __version__ as __ccpversion__

      File "/opt/virtual_env/py34_test/build/ciscoconfparse/version_info/__init__.py", line 1, in <module>

        from version import *

    ImportError: No module named 'version'

    ----------------------------------------
    Cleaning up...
    Command python setup.py egg_info failed with error code 1 in /opt/virtual_env/py34_test/build/ciscoconfparse
    Storing debug log for failure in /home/mpenning/.pip/pip.log
    (py34_test)[mpenning@tsunami this]$

**Comment by mpenning** [comment]
This is fixed in ciscoconfparse 1.2.13.
