### ISSUE TITLE
[Unreproducable Bug]: Brace parsing too eager

### ISSUE THREAD

**Issue by icovada** [mpenning/ciscoconfparse#251]
### Contact Details

comments in this issue

### What happened?

While parsing a cisco configuration with a wrongly indentated exclamation mark, the new brace parsing function is engaged and crashes

### CiscoConfParse Version

1.6.47

### What Operating System are you using?

Linux - Debian, Ubuntu, CentOS, RHEL or others

### What Python version(s) have this problem?

Python 3.10

### Show us how to reproduce the problem.  Please tell us if the problem is specific to certain inputs or situations.

```python
from ciscoconfparse import CiscoConfParse
config = """
!
!
module provision switch 1
 slot 1 slot-type 333 port-type 113 number 4 port-type 60 number 16  virtual-slot 17
 slot 3 slot-type 318 port-type 31 number 3 port-type 60 number 2  virtual-slot 19
 slot 5 slot-type 372 port-type 60 number 16 port-type 113 number 4  virtual-slot 21
 !
module provision switch 2
 slot 1 slot-type 333 port-type 113 number 4 port-type 60 number 16  virtual-slot 33
 slot 3 slot-type 318 port-type 31 number 3 port-type 60 number 2  virtual-slot 35
 slot 5 slot-type 372 port-type 60 number 16 port-type 113 number 4  virtual-slot 37
 
!

end
"""
a = CiscoConfParse(config.split("\n"))
```

### Python tracebacks

```shell
2022-10-20 16:38:08.271 | ERROR    | ciscoconfparse.ciscoconfparse:_bootstrap_obj_init_ios:5325 - An error has been caught in function '_bootstrap_obj_init_ios', process 'MainProcess' (94993), thread 'MainThread' (139862499737600):
Traceback (most recent call last):

  File "<stdin>", line 1, in <module>
  File "/home/federico/git/netwalk/.venv/lib/python3.10/site-packages/ciscoconfparse/ciscoconfparse.py", line 505, in __init__
    self.ConfigObjs = ConfigList(
    │    │            └ <class 'ciscoconfparse.ciscoconfparse.ConfigList'>
    │    └ None
    └ <CiscoConfParse: None lines / syntax: ios / comment delimiter: '!' / factory: False / encoding: 'UTF-8'>
  File "/home/federico/git/netwalk/.venv/lib/python3.10/site-packages/ciscoconfparse/ciscoconfparse.py", line 4453, in __init__
    self._list = self._bootstrap_obj_init_ios(initlist)
    │    │       │    │                       └ ['', '!', '!', 'module provision switch 1', ' slot 1 slot-type 333 port-type 113 number 4 port-type 60 number 16  virtual-slo...
    │    │       │    └ <function ConfigList._bootstrap_obj_init_ios at 0x7f344501f9a0>
    │    │       └ <ConfigList, syntax='ios', comment='!', conf=[<IOSCfgLine # 0 ''>, <IOSCfgLine # 1 '!'>, <IOSCfgLine # 2 '!'>, <IOSCfgLine # ...
    │    └ [<IOSCfgLine # 0 ''>, <IOSCfgLine # 1 '!'>, <IOSCfgLine # 2 '!'>, <IOSCfgLine # 3 'module provision switch 1'>, <IOSCfgLine #...
    └ <ConfigList, syntax='ios', comment='!', conf=[<IOSCfgLine # 0 ''>, <IOSCfgLine # 1 '!'>, <IOSCfgLine # 2 '!'>, <IOSCfgLine # ...
> File "/home/federico/git/netwalk/.venv/lib/python3.10/site-packages/ciscoconfparse/ciscoconfparse.py", line 5325, in _bootstrap_obj_init_ios
    self._list = assign_parent_to_closing_braces(input_list=self._list)
    │    │       │                                          │    └ [<IOSCfgLine # 0 ''>, <IOSCfgLine # 1 '!'>, <IOSCfgLine # 2 '!'>, <IOSCfgLine # 3 'module provision switch 1'>, <IOSCfgLine #...
    │    │       │                                          └ <ConfigList, syntax='ios', comment='!', conf=[<IOSCfgLine # 0 ''>, <IOSCfgLine # 1 '!'>, <IOSCfgLine # 2 '!'>, <IOSCfgLine # ...
    │    │       └ <function assign_parent_to_closing_braces at 0x7f3444ffcf70>
    │    └ [<IOSCfgLine # 0 ''>, <IOSCfgLine # 1 '!'>, <IOSCfgLine # 2 '!'>, <IOSCfgLine # 3 'module provision switch 1'>, <IOSCfgLine #...
    └ <ConfigList, syntax='ios', comment='!', conf=[<IOSCfgLine # 0 ''>, <IOSCfgLine # 1 '!'>, <IOSCfgLine # 2 '!'>, <IOSCfgLine # ...
  File "/home/federico/git/netwalk/.venv/lib/python3.10/site-packages/ciscoconfparse/ciscoconfparse.py", line 344, in assign_parent_to_closing_braces
    if len(obj.text)>=1 and obj.text.rstrip()[-1] == '{':
           │   │            │   └ <property object at 0x7f3445119e90>
           │   │            └ <IOSCfgLine # 12 ' ' (parent is # 8)>
           │   └ <property object at 0x7f3445119e90>
           └ <IOSCfgLine # 12 ' ' (parent is # 8)>

IndexError: string index out of range
  File "<stdin>", line 1, in <module>
2022-10-20 16:38:08.272 | ERROR    | __main__:<module>:1 - An error has been caught in function '<module>', process 'MainProcess' (94993), thread 'MainThread' (139862499737600):
Traceback (most recent call last):

> File "<stdin>", line 1, in <module>
  File "/home/federico/git/netwalk/.venv/lib/python3.10/site-packages/ciscoconfparse/ciscoconfparse.py", line 505, in __init__
    self.ConfigObjs = ConfigList(
    │    │            └ <class 'ciscoconfparse.ciscoconfparse.ConfigList'>
    │    └ None
    └ <CiscoConfParse: None lines / syntax: ios / comment delimiter: '!' / factory: False / encoding: 'UTF-8'>
  File "/home/federico/git/netwalk/.venv/lib/python3.10/site-packages/ciscoconfparse/ciscoconfparse.py", line 4453, in __init__
    self._list = self._bootstrap_obj_init_ios(initlist)
    │    │       │    │                       └ ['', '!', '!', 'module provision switch 1', ' slot 1 slot-type 333 port-type 113 number 4 port-type 60 number 16  virtual-slo...
    │    │       │    └ <function ConfigList._bootstrap_obj_init_ios at 0x7f344501f9a0>
    │    │       └ <ConfigList, syntax='ios', comment='!', conf=[<IOSCfgLine # 0 ''>, <IOSCfgLine # 1 '!'>, <IOSCfgLine # 2 '!'>, <IOSCfgLine # ...
    │    └ [<IOSCfgLine # 0 ''>, <IOSCfgLine # 1 '!'>, <IOSCfgLine # 2 '!'>, <IOSCfgLine # 3 'module provision switch 1'>, <IOSCfgLine #...
    └ <ConfigList, syntax='ios', comment='!', conf=[<IOSCfgLine # 0 ''>, <IOSCfgLine # 1 '!'>, <IOSCfgLine # 2 '!'>, <IOSCfgLine # ...
  File "/home/federico/git/netwalk/.venv/lib/python3.10/site-packages/ciscoconfparse/ciscoconfparse.py", line 5325, in _bootstrap_obj_init_ios
    self._list = assign_parent_to_closing_braces(input_list=self._list)
    │    │       │                                          │    └ [<IOSCfgLine # 0 ''>, <IOSCfgLine # 1 '!'>, <IOSCfgLine # 2 '!'>, <IOSCfgLine # 3 'module provision switch 1'>, <IOSCfgLine #...
    │    │       │                                          └ <ConfigList, syntax='ios', comment='!', conf=[<IOSCfgLine # 0 ''>, <IOSCfgLine # 1 '!'>, <IOSCfgLine # 2 '!'>, <IOSCfgLine # ...
    │    │       └ <function assign_parent_to_closing_braces at 0x7f3444ffcf70>
    │    └ [<IOSCfgLine # 0 ''>, <IOSCfgLine # 1 '!'>, <IOSCfgLine # 2 '!'>, <IOSCfgLine # 3 'module provision switch 1'>, <IOSCfgLine #...
    └ <ConfigList, syntax='ios', comment='!', conf=[<IOSCfgLine # 0 ''>, <IOSCfgLine # 1 '!'>, <IOSCfgLine # 2 '!'>, <IOSCfgLine # ...
  File "/home/federico/git/netwalk/.venv/lib/python3.10/site-packages/ciscoconfparse/ciscoconfparse.py", line 344, in assign_parent_to_closing_braces
    if len(obj.text)>=1 and obj.text.rstrip()[-1] == '{':
           │   │            │   └ <property object at 0x7f3445119e90>
           │   │            └ <IOSCfgLine # 12 ' ' (parent is # 8)>
           │   └ <property object at 0x7f3445119e90>
           └ <IOSCfgLine # 12 ' ' (parent is # 8)>

IndexError: string index out of range
  File "/home/federico/git/netwalk/.venv/lib/python3.10/site-packages/loguru/_logger.py", line 1226, in catch_wrapper
    return function(*args, **kwargs)
  File "/home/federico/git/netwalk/.venv/lib/python3.10/site-packages/ciscoconfparse/ciscoconfparse.py", line 505, in __init__
    self.ConfigObjs = ConfigList(
  File "/home/federico/git/netwalk/.venv/lib/python3.10/site-packages/ciscoconfparse/ciscoconfparse.py", line 4453, in __init__
    self._list = self._bootstrap_obj_init_ios(initlist)
  File "/home/federico/git/netwalk/.venv/lib/python3.10/site-packages/ciscoconfparse/ciscoconfparse.py", line 5325, in _bootstrap_obj_init_ios
    self._list = assign_parent_to_closing_braces(input_list=self._list)
  File "/home/federico/git/netwalk/.venv/lib/python3.10/site-packages/loguru/_logger.py", line 1226, in catch_wrapper
    return function(*args, **kwargs)
  File "/home/federico/git/netwalk/.venv/lib/python3.10/site-packages/ciscoconfparse/ciscoconfparse.py", line 344, in assign_parent_to_closing_braces
    if len(obj.text)>=1 and obj.text.rstrip()[-1] == '{':
IndexError: string index out of range
```

### Relevant log output

```shell
File "/home/federico/git/netwalk/.venv/lib/python3.10/site-packages/ciscoconfparse/ciscoconfparse.py", line 344, in assign_parent_to_closing_braces
    if len(obj.text)>=1 and obj.text.rstrip()[-1] == '{':
IndexError: string index out of range
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mpenning/ciscoconfparse/blob/main/CONTRIBUTING.md)

**Comment by mpenning** [comment]
I'm running debian bullseye with python3.9 and python3.10 in virtualenvs... I cannot reproduce this problem.

```shell
[mpenning@mudslide ~]$ uname -a
Linux mudslide 5.10.0-19-amd64 #1 SMP Debian 5.10.149-1 (2022-10-17) x86_64 GNU/Linux
[mpenning@mudslide ~]$
```

Contents of my bug reproduction script... `gh_251.py`...
```python
# filename: gh_251.py
from ciscoconfparse import CiscoConfParse
config = """
!
!
module provision switch 1
 slot 1 slot-type 333 port-type 113 number 4 port-type 60 number 16  virtual-slot 17
 slot 3 slot-type 318 port-type 31 number 3 port-type 60 number 2  virtual-slot 19
 slot 5 slot-type 372 port-type 60 number 16 port-type 113 number 4  virtual-slot 21
 !
module provision switch 2
 slot 1 slot-type 333 port-type 113 number 4 port-type 60 number 16  virtual-slot 33
 slot 3 slot-type 318 port-type 31 number 3 port-type 60 number 2  virtual-slot 35
 slot 5 slot-type 372 port-type 60 number 16 port-type 113 number 4  virtual-slot 37

!

end
"""
parse = CiscoConfParse(config.split("\n"))
parse_w_noblank = CiscoConfParse(config.splitlines(), ignore_blank_lines=False)
parse_w_blank = CiscoConfParse(config.splitlines(), ignore_blank_lines=True)
print(parse)
print(parse_w_noblank)
print(parse_w_blank)
```

Using python3.9...
```shell
[mpenning@mudslide ~]$ workon py39_test
(py39_test) [mpenning@mudslide ~]$ which python
/opt/virtual_env/py39_test/bin/python
(py39_test) [mpenning@mudslide ~]$
(py39_test) [mpenning@mudslide ~]$ python ./gh_251.py
<CiscoConfParse: 13 lines / syntax: ios / comment delimiter: '!' / factory: False / encoding: 'UTF-8'>
<CiscoConfParse: 16 lines / syntax: ios / comment delimiter: '!' / factory: False / encoding: 'UTF-8'>
<CiscoConfParse: 13 lines / syntax: ios / comment delimiter: '!' / factory: False / encoding: 'UTF-8'>
(py39_test) [mpenning@mudslide ~]$
```

Using python3.10...
```shell
(py39_test) [mpenning@mudslide ~]$ workon py310_test
(py310_test) [mpenning@mudslide ~]$ which python
/opt/virtual_env/py310_test/bin/python
(py310_test) [mpenning@mudslide ~]$
(py310_test) [mpenning@mudslide ~]$ python -V
Python 3.10.8
(py310_test) [mpenning@mudslide ~]$
(py310_test) [mpenning@mudslide ~]$ python ./gh_251.py
<CiscoConfParse: 13 lines / syntax: ios / comment delimiter: '!' / factory: False / encoding: 'UTF-8'>
<CiscoConfParse: 16 lines / syntax: ios / comment delimiter: '!' / factory: False / encoding: 'UTF-8'>
<CiscoConfParse: 13 lines / syntax: ios / comment delimiter: '!' / factory: False / encoding: 'UTF-8'>
(py310_test) [mpenning@mudslide ~]$
```

**Comment by mpenning** [comment]
I'm not 100%  sure why you hit this bug, but I added a commit that should fix the math problem in `assign_parent_to_closing_braces()` below...

This could be buggy in some situations...
```python
if len(obj.text)>=1 and obj.text.rstrip()[-1] == '{'
```

I changed it to use `rstrip()` in both comparisons...
```python
if len(obj.text.rstrip())>=1 and obj.text.rstrip()[-1] == '{'
```

I think this will fix the problem... not sure.  Please test with 1.6.48... soon to be posted to pypi.

**Comment by ntac-mark** [comment]
I was running into this bug, but with my banners that had a blank line with 10 or so blank spaces. 
Your fix works, just make sure you apply the same thing to two lines later for
`.           elif len(obj.text.lstrip())>=1 and obj.text.lstrip()[0]=='}':`

Thank you!

**Comment by mpenning** [comment]
> Your fix works, just make sure you apply the same thing to two lines later

I changed all the string comparisons in `assign_parent_to_closing_braces()`... in the second comparison that you referenced I use `strip()` instead of `lstrip()`, but the end result should address the point you mentioned...
