### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'dns'

### ISSUE THREAD

**Issue by beejaz** [mpenning/ciscoconfparse#254]
### Contact Details

Github please

### What happened?

Hi,

Using ciscoconfparse 1.6.51 gives current error during our build process now. It worked without problems in 1.6.50, reverting to this version solves the problem for me.

```
  File "/usr/local/lib/python3.9/site-packages/napalm/base/helpers.py", line 19, in <module>
    from ciscoconfparse import CiscoConfParse
  File "/usr/local/lib/python3.9/site-packages/ciscoconfparse/__init__.py", line 29, in <module>
    from ciscoconfparse.ccp_util import PythonOptimizeCheck
  File "/usr/local/lib/python3.9/site-packages/ciscoconfparse/ccp_util.py", line 39, in <module>
    from dns.exception import DNSException
ModuleNotFoundError: No module named 'dns'
```

I believe this might be caused by this commit
https://github.com/mpenning/ciscoconfparse/commit/3ce2a1dfb67046f8205207b94e8c9fb92a5ad0d4#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L44
that removes these:
```
dependencies = [
    "passlib=^1.7.4",
    "dnspython=^2.1.0",
    "loguru=0.6.0",
    "toml=0.10.2",
]
```` 

### CiscoConfParse Version

1.6.51

### What Operating System are you using?

Linux - Debian, Ubuntu, CentOS, RHEL or others

### What Python version(s) have this problem?

Python 3.9

### Show us how to reproduce the problem.  Please tell us if the problem is specific to certain inputs or situations.

```python
Importing package
```

### Python tracebacks

```shell
$ python3 tests/verify_templates.py
Traceback (most recent call last):
  File "/builds/ntm/tests/verify_templates.py", line 6, in <module>
    from app.service.ntm import NetworkTemplateManager
  File "/builds/ntm/./app/service/ntm.py", line 13, in <module>
    from app.helpers import nb_initiate, load_yaml_file, MatterMost, napalm_initiate, napalm_merge_config
  File "/builds/ntm/./app/helpers.py", line 5, in <module>
    from napalm import get_network_driver
  File "/usr/local/lib/python3.9/site-packages/napalm/__init__.py", line 3, in <module>
    from napalm.base import get_network_driver
  File "/usr/local/lib/python3.9/site-packages/napalm/base/__init__.py", line 27, in <module>
    from napalm.base.base import NetworkDriver
  File "/usr/local/lib/python3.9/site-packages/napalm/base/base.py", line 25, in <module>
    import napalm.base.helpers
  File "/usr/local/lib/python3.9/site-packages/napalm/base/helpers.py", line 19, in <module>
    from ciscoconfparse import CiscoConfParse
  File "/usr/local/lib/python3.9/site-packages/ciscoconfparse/__init__.py", line 29, in <module>
    from ciscoconfparse.ccp_util import PythonOptimizeCheck
  File "/usr/local/lib/python3.9/site-packages/ciscoconfparse/ccp_util.py", line 39, in <module>
    from dns.exception import DNSException
ModuleNotFoundError: No module named 'dns'
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mpenning/ciscoconfparse/blob/main/CONTRIBUTING.md)

**Comment by mpenning** [comment]
As you may have seen, I fixed the build problem and added a Github CI test to try to detect this problem after releasing.

Refs:
- https://github.com/mpenning/ciscoconfparse/commit/bad2ea67169b657065740828213f6fc180dfb287
- https://github.com/mpenning/ciscoconfparse/commit/bad2ea67169b657065740828213f6fc180dfb287

The next step is building something in my local unittests to do the same.

**Comment by beejaz** [comment]
Hi, thank you for quick response!

I tried it out with ciscoconfparse-1.6.52 and it worked as it was expected again 👍
