### ISSUE TITLE
[Bug]: Using append_line() causes issues

### ISSUE THREAD

**Issue by troyholder** [mpenning/ciscoconfparse#290]
### What happened?

Append a line with `append_line()` and run `atomic()` fails. I am seeing the issue with Python versions 3.10 through 3.12.

### CiscoConfParse Version

1.9.16

### What Operating System are you using?

MacOS

### What Python version(s) have this problem?

Python 3.10, Other (please specify)

### Show us how to reproduce the problem.  Please tell us if the problem is specific to certain inputs or situations.

```python
from ciscoconfparse import CiscoConfParse
parsed = CiscoConfParse(['1'])
parsed.atomic()
parsed.append_line('2')
parsed.atomic()
```

### Python tracebacks

```shell
2023-11-01 17:21:54.111 | ERROR    | ciscoconfparse.ciscoconfparse:atomic:857 - An error has been caught in function 'atomic', process 'MainProcess' (54994), thread 'MainThread' (8044224192):
Traceback (most recent call last):

  File "/Users/redacted/tmp/cisco_conf_parse/py-3-10/lib/python3.10/site-packages/bpython/curtsiesfrontend/coderunner.py", line 185, in _blocking_run_code
    unfinished = self.interp.runsource(self.source)
                 │    │      │         │    └ 'parsed.atomic()'
                 │    │      │         └ <bpython.curtsiesfrontend.coderunner.CodeRunner object at 0x10237f850>
                 │    │      └ <function Interpreter.runsource at 0x1022f3880>
                 │    └ <bpython.curtsiesfrontend.interpreter.Interp object at 0x10229e170>
                 └ <bpython.curtsiesfrontend.coderunner.CodeRunner object at 0x10237f850>
  File "/Users/redacted/tmp/cisco_conf_parse/py-3-10/lib/python3.10/site-packages/bpython/repl.py", line 153, in runsource
    return super().runsource(source, filename, symbol)
                             │       │         └ 'single'
                             │       └ '<bpython-input-10>'
                             └ 'parsed.atomic()'

  File "/opt/homebrew/Cellar/python@3.10/3.10.13_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/code.py", line 74, in runsource
    self.runcode(code)
    │    │       └ <code object <module> at 0x102c86600, file "<bpython-input-10>", line 1>
    │    └ <function InteractiveInterpreter.runcode at 0x1010a32e0>
    └ <bpython.curtsiesfrontend.interpreter.Interp object at 0x10229e170>

  File "/opt/homebrew/Cellar/python@3.10/3.10.13_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
         │     │    └ {'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': None, '__spec__': None, '__builtins__': {'__name...
         │     └ <bpython.curtsiesfrontend.interpreter.Interp object at 0x10229e170>
         └ <code object <module> at 0x102c86600, file "<bpython-input-10>", line 1>

  File "<bpython-input-10>", line 1, in <module>
    parsed.atomic()
    │      └ <function CiscoConfParse.atomic at 0x102b196c0>
    └ <CiscoConfParse: 2 lines / syntax: ios / comment delimiter: '!' / factory: False / ignore_blank_lines: True / encoding: 'UTF-8'>
> File "/Users/redacted/tmp/cisco_conf_parse/py-3-10/lib/python3.10/site-packages/ciscoconfparse/ciscoconfparse.py", line 857, in atomic
    self.ConfigObjs._list = self.ConfigObjs._bootstrap_obj_init_ng(self.ioscfg, debug=self.debug)
    │    │          │       │    │          │                      │    │             │    └ 0
    │    │          │       │    │          │                      │    │             └ <CiscoConfParse: 2 lines / syntax: ios / comment delimiter: '!' / factory: False / ignore_blank_lines: True / encoding: 'UTF-8'>
    │    │          │       │    │          │                      │    └ <property object at 0x102b46ac0>
    │    │          │       │    │          │                      └ <CiscoConfParse: 2 lines / syntax: ios / comment delimiter: '!' / factory: False / ignore_blank_lines: True / encoding: 'UTF-8'>
    │    │          │       │    │          └ <function ConfigList._bootstrap_obj_init_ng at 0x102af3250>
    │    │          │       │    └ <ConfigList, syntax='ios', comment='!', conf=[<IOSCfgLine # 0 '1'>, '2']>
    │    │          │       └ <CiscoConfParse: 2 lines / syntax: ios / comment delimiter: '!' / factory: False / ignore_blank_lines: True / encoding: 'UTF-8'>
    │    │          └ [<IOSCfgLine # 0 '1'>, '2']
    │    └ <ConfigList, syntax='ios', comment='!', conf=[<IOSCfgLine # 0 '1'>, '2']>
    └ <CiscoConfParse: 2 lines / syntax: ios / comment delimiter: '!' / factory: False / ignore_blank_lines: True / encoding: 'UTF-8'>
  File "/Users/redacted/tmp/cisco_conf_parse/py-3-10/lib/python3.10/site-packages/ciscoconfparse/ciscoconfparse.py", line 827, in ioscfg
    return [ii.text for ii in self.ConfigObjs]
                              │    └ <ConfigList, syntax='ios', comment='!', conf=[<IOSCfgLine # 0 '1'>, '2']>
                              └ <CiscoConfParse: 2 lines / syntax: ios / comment delimiter: '!' / factory: False / ignore_blank_lines: True / encoding: 'UTF-8'>
  File "/Users/redacted/tmp/cisco_conf_parse/py-3-10/lib/python3.10/site-packages/ciscoconfparse/ciscoconfparse.py", line 827, in <listcomp>
    return [ii.text for ii in self.ConfigObjs]
            │           └ '2'
            └ '2'

AttributeError: 'str' object has no attribute 'text'
2023-11-01 17:21:54.139 | ERROR    | __main__:<module>:1 - An error has been caught in function '<module>', process 'MainProcess' (54994), thread 'MainThread' (8044224192):
Traceback (most recent call last):

  File "/Users/redacted/tmp/cisco_conf_parse/py-3-10/lib/python3.10/site-packages/bpython/curtsiesfrontend/coderunner.py", line 185, in _blocking_run_code
    unfinished = self.interp.runsource(self.source)
                 │    │      │         │    └ 'parsed.atomic()'
                 │    │      │         └ <bpython.curtsiesfrontend.coderunner.CodeRunner object at 0x10237f850>
                 │    │      └ <function Interpreter.runsource at 0x1022f3880>
                 │    └ <bpython.curtsiesfrontend.interpreter.Interp object at 0x10229e170>
                 └ <bpython.curtsiesfrontend.coderunner.CodeRunner object at 0x10237f850>
  File "/Users/redacted/tmp/cisco_conf_parse/py-3-10/lib/python3.10/site-packages/bpython/repl.py", line 153, in runsource
    return super().runsource(source, filename, symbol)
                             │       │         └ 'single'
                             │       └ '<bpython-input-10>'
                             └ 'parsed.atomic()'

  File "/opt/homebrew/Cellar/python@3.10/3.10.13_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/code.py", line 74, in runsource
    self.runcode(code)
    │    │       └ <code object <module> at 0x102c86600, file "<bpython-input-10>", line 1>
    │    └ <function InteractiveInterpreter.runcode at 0x1010a32e0>
    └ <bpython.curtsiesfrontend.interpreter.Interp object at 0x10229e170>

  File "/opt/homebrew/Cellar/python@3.10/3.10.13_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
         │     │    └ {'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': None, '__spec__': None, '__builtins__': {'__name...
         │     └ <bpython.curtsiesfrontend.interpreter.Interp object at 0x10229e170>
         └ <code object <module> at 0x102c86600, file "<bpython-input-10>", line 1>

> File "<bpython-input-10>", line 1, in <module>
    parsed.atomic()
    │      └ <function CiscoConfParse.atomic at 0x102b196c0>
    └ <CiscoConfParse: 2 lines / syntax: ios / comment delimiter: '!' / factory: False / ignore_blank_lines: True / encoding: 'UTF-8'>
  File "/Users/redacted/tmp/cisco_conf_parse/py-3-10/lib/python3.10/site-packages/ciscoconfparse/ciscoconfparse.py", line 857, in atomic
    self.ConfigObjs._list = self.ConfigObjs._bootstrap_obj_init_ng(self.ioscfg, debug=self.debug)
    │    │          │       │    │          │                      │    │             │    └ 0
    │    │          │       │    │          │                      │    │             └ <CiscoConfParse: 2 lines / syntax: ios / comment delimiter: '!' / factory: False / ignore_blank_lines: True / encoding: 'UTF-8'>
    │    │          │       │    │          │                      │    └ <property object at 0x102b46ac0>
    │    │          │       │    │          │                      └ <CiscoConfParse: 2 lines / syntax: ios / comment delimiter: '!' / factory: False / ignore_blank_lines: True / encoding: 'UTF-8'>
    │    │          │       │    │          └ <function ConfigList._bootstrap_obj_init_ng at 0x102af3250>
    │    │          │       │    └ <ConfigList, syntax='ios', comment='!', conf=[<IOSCfgLine # 0 '1'>, '2']>
    │    │          │       └ <CiscoConfParse: 2 lines / syntax: ios / comment delimiter: '!' / factory: False / ignore_blank_lines: True / encoding: 'UTF-8'>
    │    │          └ [<IOSCfgLine # 0 '1'>, '2']
    │    └ <ConfigList, syntax='ios', comment='!', conf=[<IOSCfgLine # 0 '1'>, '2']>
    └ <CiscoConfParse: 2 lines / syntax: ios / comment delimiter: '!' / factory: False / ignore_blank_lines: True / encoding: 'UTF-8'>
  File "/Users/redacted/tmp/cisco_conf_parse/py-3-10/lib/python3.10/site-packages/ciscoconfparse/ciscoconfparse.py", line 827, in ioscfg
    return [ii.text for ii in self.ConfigObjs]
                              │    └ <ConfigList, syntax='ios', comment='!', conf=[<IOSCfgLine # 0 '1'>, '2']>
                              └ <CiscoConfParse: 2 lines / syntax: ios / comment delimiter: '!' / factory: False / ignore_blank_lines: True / encoding: 'UTF-8'>
  File "/Users/redacted/tmp/cisco_conf_parse/py-3-10/lib/python3.10/site-packages/ciscoconfparse/ciscoconfparse.py", line 827, in <listcomp>
    return [ii.text for ii in self.ConfigObjs]
            │           └ '2'
            └ '2'

AttributeError: 'str' object has no attribute 'text'
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    parsed.atomic()
  File "/Users/redacted/tmp/cisco_conf_parse/py-3-10/lib/python3.10/site-packages/loguru/_logger.py", line 1277, in catch_wrapper
    return function(*args, **kwargs)
  File "/Users/redacted/tmp/cisco_conf_parse/py-3-10/lib/python3.10/site-packages/ciscoconfparse/ciscoconfparse.py", line 857, in atomic
    self.ConfigObjs._list = self.ConfigObjs._bootstrap_obj_init_ng(self.ioscfg, debug=self.debug)
  File "/Users/redacted/tmp/cisco_conf_parse/py-3-10/lib/python3.10/site-packages/loguru/_logger.py", line 1277, in catch_wrapper
    return function(*args, **kwargs)
  File "/Users/redacted/tmp/cisco_conf_parse/py-3-10/lib/python3.10/site-packages/ciscoconfparse/ciscoconfparse.py", line 827, in ioscfg
    return [ii.text for ii in self.ConfigObjs]
  File "/Users/redacted/tmp/cisco_conf_parse/py-3-10/lib/python3.10/site-packages/ciscoconfparse/ciscoconfparse.py", line 827, in <listcomp>
    return [ii.text for ii in self.ConfigObjs]
AttributeError: 'str' object has no attribute 'text'
>>>
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mpenning/ciscoconfparse/blob/main/CONTRIBUTING.md)

**Comment by kuai1001llc** [comment]
With [CiscoConfParse Version 1.9.17](https://pypi.org/project/ciscoconfparse/1.9.17/)

```python
 $ python
Python 3.10.13 (main, Nov  2 2023, 08:33:35) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ciscoconfparse import CiscoConfParse
>>> parsed = CiscoConfParse(['1'])
2023-11-02 10:06:17.882 | INFO     | ciscoconfparse.ciscoconfparse:__init__:611 - As of version 1.9.17 and later, `ignore_blank_lines=True` is only honored when `factory=True`
>>> 2023-11-02 10:06:17.882 | INFO     | ciscoconfparse.ciscoconfparse:__init__:611 - As of version 1.9.17 and later, `ignore_blank_lines=True` is only honored when `factory=True`

>>> parsed.append_line('2')
<IOSCfgLine # 1 '2'>
>>>
```
