### ISSUE TITLE
[Feature]: CiscoInterface() fails to parse IOS XR interface names (under factory=True)

### ISSUE THREAD

**Issue by Bierchermuesli** [mpenning/ciscoconfparse#291]
### What happened?

I get an infinite loop when some special interfaces (MgmtEth0, PTP0..) are present in my XR config. Whether they are disabled or not.

Python 3.10.12
ciscoconfparse  1.9.28
loguru  0.7.2

- same applies by ciscoconfparse from source.
- same happends with tests/fixtures/configs/sample_01.iosxr
- btw: how to use models_iosxr.py ?
- any XR hints I have to apply?

### CiscoConfParse Version

1.9.28

### What Operating System are you using?

Linux - Debian, Ubuntu, CentOS, RHEL or others

### What Python version(s) have this problem?

Python 3.10

### Show us how to reproduce the problem.  Please tell us if the problem is specific to certain inputs or situations.

```python
from ciscoconfparse import CiscoConfParse

int_bad="""
interface MgmtEth0/RSP0/CPU0/0
 description IP-for-OutbandManagement 
 ipv4 address 172.11.111.1 255.255.255.0
 shutdown
 ipv4 flowspec disable
 ipv6 flowspec disable
!
interface MgmtEth0/RSP0/CPU0/1
 shutdown
!
interface MgmtEth0/RSP1/CPU0/0
 description IP-for-OutbandManagement 
 shutdown
!
interface MgmtEth0/RSP1/CPU0/1
 shutdown
 !
interface PTP0/RSP0/CPU0/0
 shutdown
!
interface preconfigure PTP0/RSP1/CPU0/0
 shutdown
"""

parse = CiscoConfParse(int_bad.splitlines(), syntax='ios', factory=True)
int = parse.find_objects_wo_child(r"^interf", r"^\s+^shutdown")

print(int)
```

### Python tracebacks

```shell
>>> cfg_parsed.find_objects_wo_child(r"^interf", r"^\s+^shutdown")
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=252, microseconds=302722), 'exception': (type=<class 'ciscoconfparse.errors.InvalidCiscoInterface'>, value=InvalidCiscoInterface("intf_dict={'prefix': 'PTP', 'digit_separator': '/', 'slot': 0, 'card': None, 'port': None, 'subinterface': None, 'channel': None, 'interface_class': None}"), traceback=<traceback object at 0x7f61d4cd7580>), 'extra': {}, 'file': (name='ccp_util.py', path='/home/me/.local/lib/python3.10/site-packages/ciscoconfparse/ccp_util.py'), 'function': '__init__', 'level': (name='ERROR', no=40, icon='❌'), 'line': 3070, 'message': "An error has been caught in function '__init__', process 'MainProcess' (131895), thread 'MainThread' (140058233954304):", 'module': 'ccp_util', 'name': 'ciscoconfparse.ccp_util', 'process': (id=131895, name='MainProcess'), 'thread': (id=140058233954304, name='MainThread'), 'time': datetime(2023, 11, 14, 11, 2, 54, 598297, tzinfo=datetime.timezone(datetime.timedelta(seconds=3600), 'CET'))}
Traceback (most recent call last):
  File "/home/me/.local/lib/python3.10/site-packages/loguru/_logger.py", line 1277, in catch_wrapper
    return function(*args, **kwargs)
  File "/home/me/.local/lib/python3.10/site-packages/ciscoconfparse/ccp_util.py", line 3161, in update_internal_state
    raise InvalidCiscoInterface(f"intf_dict={intf_dict}")
ciscoconfparse.errors.InvalidCiscoInterface: intf_dict={'prefix': 'PTP', 'digit_separator': '/', 'slot': 0, 'card': None, 'port': None, 'subinterface': None, 'channel': None, 'interface_class': None}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/me/.local/lib/python3.10/site-packages/loguru/_logger.py", line 1277, in catch_wrapper
    return function(*args, **kwargs)
  File "/home/me/.local/lib/python3.10/site-packages/ciscoconfparse/ccp_util.py", line 3161, in update_internal_state
    raise InvalidCiscoInterface(f"intf_dict={intf_dict}")
ciscoconfparse.errors.InvalidCiscoInterface: intf_dict={'prefix': 'PTP', 'digit_separator': '/', 'slot': 0, 'card': None, 'port': None, 'subinterface': None, 'channel': None, 'interface_class': None}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/me/.local/lib/python3.10/site-packages/loguru/_logger.py", line 1277, in catch_wrapper
    return function(*args, **kwargs)
  File "/home/me/.local/lib/python3.10/site-packages/ciscoconfparse/ccp_util.py", line 3161, in update_internal_state
    raise InvalidCiscoInterface(f"intf_dict={intf_dict}")
ciscoconfparse.errors.InvalidCiscoInterface: intf_dict={'prefix': 'PTP', 'digit_separator': '/', 'slot': 0, 'card': None, 'port': None, 'subinterface': None, 'channel': None, 'interface_class': None}

During handling of the above exception, another exception occurred:
...
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mpenning/ciscoconfparse/blob/main/CONTRIBUTING.md)

**Comment by mpenning** [comment]
Thank you for filing a bug.  To be exact, `ciscoconfparse.ccp_util.CiscoInterface` chokes on IOS XR interface names right now... it also happens with my git HEAD as shown below...

Have you been using `IOS XR` factory before now?

The most basic problem is that IOS XR factory is not part of the test suite; it would have caught this problem if it was.

This is a bit complicated to fix because it seems that IOS XR makes completely different assumptions about how interfaces are rendered... one does not expect that "MgmtEth0" would come before "RP0" in other IOS-style configs... nevertheless I will try to fix this, but I need to do some reading about IOS XR interface names to do so.

```python
$ python
Python 3.10.13 (main, Nov  2 2023, 08:33:35) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ciscoconfparse.ccp_util import CiscoInterface
>>> CiscoInterface("MgmtEth0/RP0/CPU0/0")
2023-11-14 04:57:48.873 | ERROR    | ciscoconfparse.ccp_util:__init__:3070 - An error has been caught in function '__init__', process 'MainProcess' (5229), thread 'MainThread' (139841872544384):
Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

> File "/home/mpenning/fixme/ciscoconfparse/ciscoconfparse/ccp_util.py", line 3070, in __init__
    self.update_internal_state(intf_dict=intf_dict)
    │    │                               └ {'prefix': 'MgmtEth', 'digit_separator': '/', 'slot': 0, 'card': None, 'port': None, 'subinterface': None, 'channel': None, '...
    │    └ <function CiscoInterface.update_internal_state at 0x7f2f77de0e50>
    └ <CiscoInterface None__UNINITIALIZED_NUMBER_ATTRIBUTE__>

  File "/home/mpenning/fixme/ciscoconfparse/ciscoconfparse/ccp_util.py", line 3161, in update_internal_state
    raise InvalidCiscoInterface(f"intf_dict={intf_dict}")
          └ <class 'ciscoconfparse.errors.InvalidCiscoInterface'>

ciscoconfparse.errors.InvalidCiscoInterface: intf_dict={'prefix': 'MgmtEth', 'digit_separator': '/', 'slot': 0, 'card': None, 'port': None, 'subinterface': None, 'channel': None, 'interface_class': None}
2023-11-14 04:57:48.887 | ERROR    | __main__:<module>:1 - An error has been caught in function '<module>', process 'MainProcess' (5229), thread 'MainThread' (139841872544384):
Traceback (most recent call last):

> File "<stdin>", line 1, in <module>

  File "/home/mpenning/fixme/ciscoconfparse/ciscoconfparse/ccp_util.py", line 3070, in __init__
    self.update_internal_state(intf_dict=intf_dict)
    │    │                               └ {'prefix': 'MgmtEth', 'digit_separator': '/', 'slot': 0, 'card': None, 'port': None, 'subinterface': None, 'channel': None, '...
    │    └ <function CiscoInterface.update_internal_state at 0x7f2f77de0e50>
    └ <CiscoInterface None__UNINITIALIZED_NUMBER_ATTRIBUTE__>

  File "/home/mpenning/fixme/ciscoconfparse/ciscoconfparse/ccp_util.py", line 3161, in update_internal_state
    raise InvalidCiscoInterface(f"intf_dict={intf_dict}")
          └ <class 'ciscoconfparse.errors.InvalidCiscoInterface'>

ciscoconfparse.errors.InvalidCiscoInterface: intf_dict={'prefix': 'MgmtEth', 'digit_separator': '/', 'slot': 0, 'card': None, 'port': None, 'subinterface': None, 'channel': None, 'interface_class': None}
2023-11-14 04:57:48.873 | ERROR    | ciscoconfparse.ccp_util:__init__:3070 - An error has been caught in function '__init__', process 'MainProcess' (5229), thread 'MainThread' (139841872544384):
Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

> File "/home/mpenning/fixme/ciscoconfparse/ciscoconfparse/ccp_util.py", line 3070, in __init__
    self.update_internal_state(intf_dict=intf_dict)
    │    │                               └ {'prefix': 'MgmtEth', 'digit_separator': '/', 'slot': 0, 'card': None, 'port': None, 'subinterface': None, 'channel': None, '...
    │    └ <function CiscoInterface.update_internal_state at 0x7f2f77de0e50>
    └ <CiscoInterface None__UNINITIALIZED_NUMBER_ATTRIBUTE__>

  File "/home/mpenning/fixme/ciscoconfparse/ciscoconfparse/ccp_util.py", line 3161, in update_internal_state
    raise InvalidCiscoInterface(f"intf_dict={intf_dict}")
          └ <class 'ciscoconfparse.errors.InvalidCiscoInterface'>

ciscoconfparse.errors.InvalidCiscoInterface: intf_dict={'prefix': 'MgmtEth', 'digit_separator': '/', 'slot': 0, 'card': None, 'port': None, 'subinterface': None, 'channel': None, 'interface_class': None}
2023-11-14 04:57:48.887 | ERROR    | __main__:<module>:1 - An error has been caught in function '<module>', process 'MainProcess' (5229), thread 'MainThread' (139841872544384):
Traceback (most recent call last):

> File "<stdin>", line 1, in <module>

  File "/home/mpenning/fixme/ciscoconfparse/ciscoconfparse/ccp_util.py", line 3070, in __init__
    self.update_internal_state(intf_dict=intf_dict)
    │    │                               └ {'prefix': 'MgmtEth', 'digit_separator': '/', 'slot': 0, 'card': None, 'port': None, 'subinterface': None, 'channel': None, '...
    │    └ <function CiscoInterface.update_internal_state at 0x7f2f77de0e50>
    └ <CiscoInterface None__UNINITIALIZED_NUMBER_ATTRIBUTE__>

  File "/home/mpenning/fixme/ciscoconfparse/ciscoconfparse/ccp_util.py", line 3161, in update_internal_state
    raise InvalidCiscoInterface(f"intf_dict={intf_dict}")
          └ <class 'ciscoconfparse.errors.InvalidCiscoInterface'>

ciscoconfparse.errors.InvalidCiscoInterface: intf_dict={'prefix': 'MgmtEth', 'digit_separator': '/', 'slot': 0, 'card': None, 'port': None, 'subinterface': None, 'channel': None, 'interface_class': None}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/virtual_env/py310_test/lib/python3.10/site-packages/loguru/_logger.py", line 1277, in catch_wrapper
    return function(*args, **kwargs)
  File "/home/mpenning/fixme/ciscoconfparse/ciscoconfparse/ccp_util.py", line 3070, in __init__
    self.update_internal_state(intf_dict=intf_dict)
  File "/opt/virtual_env/py310_test/lib/python3.10/site-packages/loguru/_logger.py", line 1277, in catch_wrapper
    return function(*args, **kwargs)
  File "/home/mpenning/fixme/ciscoconfparse/ciscoconfparse/ccp_util.py", line 3161, in update_internal_state
    raise InvalidCiscoInterface(f"intf_dict={intf_dict}")
ciscoconfparse.errors.InvalidCiscoInterface: intf_dict={'prefix': 'MgmtEth', 'digit_separator': '/', 'slot': 0, 'card': None, 'port': None, 'subinterface': None, 'channel': None, 'interface_class': None}
```

**Comment by mpenning** [comment]
This is not relevant to the bug, but you should not overwrite python functions... this is overwriting `int()`...

```python
parse = CiscoConfParse(int_bad.splitlines(), syntax='ios', factory=True)
int = parse.find_objects_wo_child(r"^interf", r"^\s+^shutdown")
```

**Comment by mpenning** [comment]
I just pushed version 1.9.29 and added new `syntax='iosxr'`...

Parsing an IOS XR config from the test fixtures works with 1.9.29...

```python
from ciscoconfparse import CiscoConfParse

parse = CiscoConfParse("tests/fixtures/configs/sample_01.iosxr", syntax='iosxr', factory=True)
active_intfs = parse.find_objects_wo_child(r"^interf", r"^\s+shutdown")
```

Please consider adding your sanitized IOS XR configs since I only have one in the test fixtures at the moment...

**Comment by Bierchermuesli** [comment]
Hey, thanks a lot for your quick response!

> Have you been using IOS XR factory before now?

Yes, `syntax='iosxr', factory=True` and it worked well. Although the problem didn't occur because I used a different filter (`parse.find_objects_w_child("^interface\s[\w\d\-\.\/]*$", "ipv\d\saddress.*")?`) and just some simple attributes (e.g. iface.name). While debugging my old code, I noticed the chocking can also happend on some attributes. e.g. simply hovering over some attributes in vscode. 

Anyway. with 1.9.29 it works well. Although lot of attributes are missing - but this might be another topic.  

I can supply some XR ASR/NCS 6.3/7.2/7.10 configs. please advice whats your preffered way.

**Comment by mpenning** [comment]
>  can supply some XR ASR/NCS 6.3/7.2/7.10 configs. please advice whats your preffered way.

Please send as text file attachments to my gmail, penningtonthing@gmail.com.

> Although lot of attributes are missing - but this might be another topic.

Any missing IOS XR attributes are another topic.

I also just added version 1.9.31 to pypi.

**Comment by mpenning** [comment]
@Bierchermuesli thank you for donating the following configs via email:

- [sample_05.iosxr][1]
- [sample_06.iosxr][2]
- [sample_07.iosxr][3]

[1]: https://github.com/mpenning/ciscoconfparse/blob/main/tests/fixtures/configs/sample_05.iosxr
[2]: https://github.com/mpenning/ciscoconfparse/blob/main/tests/fixtures/configs/sample_06.iosxr
[3]: https://github.com/mpenning/ciscoconfparse/blob/main/tests/fixtures/configs/sample_07.iosxr
