### ISSUE TITLE
CiscoConfParse does not accept unicode paths

### ISSUE THREAD

**Issue by mpenning** [mpenning/ciscoconfparse#33]
Unicode paths are not accepted; this needs to be fixed.

    (py27_test)[mpenning@tsunami fast]$ python
    Python 2.7.3 (default, Jan  2 2013, 13:56:14) 
    [GCC 4.7.2] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from ciscoconfparse import CiscoConfParse
    >>> config = u'configs/sample_01.ios'
    >>> parse = CiscoConfParse(config)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "ciscoconfparse/ciscoconfparse.py", line 199, in __init__
        " an invalid argument\n")
    RuntimeError: [FATAL] CiscoConfParse() received an invalid argument
    
    >>>

**Comment by mpenning** [comment]
Fixed in 1.2.19
