### ISSUE TITLE
ValueError: Could not parse 'ipv6 router ospf 6'

### ISSUE THREAD

**Issue by mzi77** [mpenning/ciscoconfparse#44]
Hi,

ciscoconfparse-1.2.37-py2.7.egg

can't parse

ipv6 router ospf 6

in IOS configuration.

**Comment by mzi77** [comment]
Error output
Traceback (most recent call last):
  File "./hsrp_check.py", line 31, in <module>
    parse = CiscoConfParse(full_path, factory=True)
  File "/usr/lib/python2.7/site-packages/ciscoconfparse-1.2.37-py2.7.egg/ciscoconfparse/ciscoconfparse.py", line 186, in __init__
    CiscoConfParse=self)
  File "/usr/lib/python2.7/site-packages/ciscoconfparse-1.2.37-py2.7.egg/ciscoconfparse/ciscoconfparse.py", line 2212, in __init__
    self._list = self._bootstrap_obj_init(data)
  File "/usr/lib/python2.7/site-packages/ciscoconfparse-1.2.37-py2.7.egg/ciscoconfparse/ciscoconfparse.py", line 2436, in _bootstrap_obj_init
    syntax='ios')
  File "/usr/lib/python2.7/site-packages/ciscoconfparse-1.2.37-py2.7.egg/ciscoconfparse/ciscoconfparse.py", line 2985, in ConfigLineFactory
    comment_delimiter=comment_delimiter) # instance of the proper subclass
  File "/usr/lib/python2.7/site-packages/ciscoconfparse-1.2.37-py2.7.egg/ciscoconfparse/models_cisco.py", line 1570, in __init__
    raise ValueError("Could not parse '{0}'".format(self.text))
ValueError: Could not parse 'ipv6 router ospf 6'

**Comment by mpenning** [comment]
Hello, I fixed this in version 1.2.40 on pypi... please update your installation and test again.
