### ISSUE TITLE
Fail to install ciscoconfparse on Windows 10

### ISSUE THREAD

**Issue by frankly0** [mpenning/ciscoconfparse#50]
C:\Python27>python.exe Lib\site-packages\ciscoconfparse\setup.py
Traceback (most recent call last):
  File "Lib\site-packages\ciscoconfparse\setup.py", line 14, in <module>
    from version_info.version import __version__ as __ccpversion__
  File "C:\Python27\Lib\site-packages\ciscoconfparse\version_info\__init__.py", line 1, in <module>
    from .version import *
  File "C:\Python27\Lib\site-packages\ciscoconfparse\version_info\version.py", line 1
    ../ciscoconfparse/version.py
    ^
SyntaxError: invalid syntax

**Comment by mpenning** [comment]
Please try installing with [pip](https://pypi.python.org/pypi/pip):

       pip install --upgrade ciscoconfparse

**Comment by frankly0** [comment]
http://prntscr.com/95i1wf

I still fail to setup python

**Comment by mpenning** [comment]
Since you are running Windows 10, try the solution described here:

http://stackoverflow.com/a/31065211/667301

    python -m pip install ciscoconfparse

**Comment by frankly0** [comment]
it works now, thanks
