### ISSUE TITLE
Regex conflict with asteriks in description element

### ISSUE THREAD

**Issue by APTEM09** [mpenning/ciscoconfparse#95]
Hello,

I have tried to children the following children element of an interface:
interface Ethernet1/1
 description ** MY DESCRIPTION **

Need a preprocessor to fix it.

```
cisco_config = CiscoConfParse(path_to_configuration_file)
int_config = cisco_config.find_objects("^interface")
int_config[4].delete_children_matching("description ** MY DESCRIPTION **")
```

```
Traceback (most recent call last):
  File "C:\__init__.py", line 28, in <module>
    int_config[4].delete_children_matching("description ** MY DESCRIPTION ")
  File "C:\Portable\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\ciscoconfparse\ccp_abc.py", line 262, in delete_children_matching
    cobjs = list(filter(methodcaller('re_search', linespec), self.children))
  File "C:\Portable\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\ciscoconfparse\ccp_abc.py", line 514, in re_search
    mm = re.search(regex, self.text)
  File "C:\Portable\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\re.py", line 182, in search
    return _compile(pattern, flags).search(string)
  File "C:\Portable\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Portable\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Portable\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Portable\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "C:\Portable\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\sre_parse.py", line 619, in _parse
    source.tell() - here + len(this))
sre_constants.error: multiple repeat at position 13
```

**Comment by mpenning** [comment]
In the configuration you posted "description ** MY DESCRIPTION **" does not have any children to delete.  Either you're doing something wrong, or you need to post more of the configuration in question.

Note: ciscoconfparse will not associate children to a parent unless the children are indented below the parent line.

**Comment by APTEM09** [comment]
Mistake from myside. Can close it.
